'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DDPro.Software.Net20.Library.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEFAULT.
        '''</summary>
        Friend ReadOnly Property str_intname_DefaultLang() As String
            Get
                Return ResourceManager.GetString("str_intname_DefaultLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to str_Meta_NewMultiVal.
        '''</summary>
        Friend ReadOnly Property str_Meta_NewMultiVal() As String
            Get
                Return ResourceManager.GetString("str_Meta_NewMultiVal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to description.
        '''</summary>
        Friend ReadOnly Property str_MetaF_Description() As String
            Get
                Return ResourceManager.GetString("str_MetaF_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to addlangtab.
        '''</summary>
        Friend ReadOnly Property str_MetaF_NewLangTab() As String
            Get
                Return ResourceManager.GetString("str_MetaF_NewLangTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to program.
        '''</summary>
        Friend ReadOnly Property str_MetaF_Programm() As String
            Get
                Return ResourceManager.GetString("str_MetaF_Programm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to programm.
        '''</summary>
        Friend ReadOnly Property str_MetaF_Programm_old() As String
            Get
                Return ResourceManager.GetString("str_MetaF_Programm_old", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update.
        '''</summary>
        Friend ReadOnly Property str_MetaF_Update() As String
            Get
                Return ResourceManager.GetString("str_MetaF_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to author.
        '''</summary>
        Friend ReadOnly Property str_MetaL_Author() As String
            Get
                Return ResourceManager.GetString("str_MetaL_Author", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to info.
        '''</summary>
        Friend ReadOnly Property str_MetaL_Info() As String
            Get
                Return ResourceManager.GetString("str_MetaL_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iso.
        '''</summary>
        Friend ReadOnly Property str_MetaL_ISO() As String
            Get
                Return ResourceManager.GetString("str_MetaL_ISO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update.
        '''</summary>
        Friend ReadOnly Property str_MetaL_LastUpdate() As String
            Get
                Return ResourceManager.GetString("str_MetaL_LastUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to name.
        '''</summary>
        Friend ReadOnly Property str_MetaL_Name() As String
            Get
                Return ResourceManager.GetString("str_MetaL_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to version.
        '''</summary>
        Friend ReadOnly Property str_MetaL_Version() As String
            Get
                Return ResourceManager.GetString("str_MetaL_Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colItemDescr.
        '''</summary>
        Friend ReadOnly Property str_xml_FileItemCol_Description() As String
            Get
                Return ResourceManager.GetString("str_xml_FileItemCol_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colItemId.
        '''</summary>
        Friend ReadOnly Property str_xml_FileItemCol_ID() As String
            Get
                Return ResourceManager.GetString("str_xml_FileItemCol_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colItemName.
        '''</summary>
        Friend ReadOnly Property str_xml_FileItemCol_Name() As String
            Get
                Return ResourceManager.GetString("str_xml_FileItemCol_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colMetaValue.
        '''</summary>
        Friend ReadOnly Property str_xml_FileMetaCol_ID() As String
            Get
                Return ResourceManager.GetString("str_xml_FileMetaCol_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colMetaData.
        '''</summary>
        Friend ReadOnly Property str_xml_FileMetaCol_Value() As String
            Get
                Return ResourceManager.GetString("str_xml_FileMetaCol_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colLangID.
        '''</summary>
        Friend ReadOnly Property str_xml_LangValCol_ID() As String
            Get
                Return ResourceManager.GetString("str_xml_LangValCol_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to colLangData.
        '''</summary>
        Friend ReadOnly Property str_xml_LangValCol_Value() As String
            Get
                Return ResourceManager.GetString("str_xml_LangValCol_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tblItemData.
        '''</summary>
        Friend ReadOnly Property str_xml_TableItemData() As String
            Get
                Return ResourceManager.GetString("str_xml_TableItemData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tblLang_.
        '''</summary>
        Friend ReadOnly Property str_xml_TableLangDataPrefix() As String
            Get
                Return ResourceManager.GetString("str_xml_TableLangDataPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tblMetaData.
        '''</summary>
        Friend ReadOnly Property str_xml_TableMetaData() As String
            Get
                Return ResourceManager.GetString("str_xml_TableMetaData", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
